### ISSUE TITLE
errors using public docker hub registry

### ISSUE THREAD

**Issue by stevebus** [jonbgallant/azure-iot-edge-dev-tool#25]
it is unclear if the tool works with a public docker hub account.   If using the below parameters for the container credentials...
CONTAINER_REGISTRY_SERVER="https://index.docker.io/v1" 
CONTAINER_REGISTRY_USERNAME="<my_docker_hub_id>"
CONTAINER_REGISTRY_PASSWORD="<my_docker_hub_pwd>"

I *think* that is the correct registry server name for public docker hub, but not sure --docs are unclear.  with the 'docker login' command, you don't need to specify a server

the iotedgedev modules --build --deploy command successfully authenticates with Docker

======== INITIALIZING CONTAINER REGISTRY ========
REGISTRY: https://index.docker.io/v1
Successfully logged into container registry: https://index.docker.io/v1

but when it tries to generate the image id, it tries to generate it in the form of
BUILDING DOCKER IMAGE: https://index.docker.io/v1/filtermodule:0.0.1-amd64

which gives this error:

Traceback (most recent call last):
  File "/usr/local/bin/iotedgedev", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/cli.py", line 294, in modules
    mod.build()
  File "/usr/local/lib/python2.7/dist-packages/iotedgedev/modules.py", line 80, in build
    tag=image_destination_name, path=".", dockerfile=docker_file_name, buildargs={"EXE_DIR": mod_proc.exe_dir})
  File "/usr/local/lib/python2.7/dist-packages/docker/models/images.py", line 172, in build
    resp = self.client.api.build(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/build.py", line 258, in build
    timeout=timeout,
  File "/usr/local/lib/python2.7/dist-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 187, in _post
    return self.post(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

Docker Hub image id's are generally of the form:   <my_docker_hub_id>\filtermodule:latest

So there may need to be special behavior to use a public docker hub registry instead of a private docker registry

**Comment by jonbgallant** [comment]
@stevebus I'm still testing this, but try setting the CONTAINER_REGISTRY_SERVER variable to your docker hub username.  Also, set CONTAINER_REGISTRY_USERNAME to username.

**Comment by stevebus** [comment]
tried it..  error below.   My environment variables in .env are set like this:

CONTAINER_REGISTRY_SERVER="stevebus" 
CONTAINER_REGISTRY_USERNAME="stevebus"
CONTAINER_REGISTRY_PASSWORD="<my docker hub password>"

![edgedev-docker-issue](https://user-images.githubusercontent.com/11857454/36906068-92d86528-1dfa-11e8-81a1-633f5cb96d22.png)

**Comment by jonbgallant** [comment]
Thanks for trying. I have a fix and will push later today. Thanks a lot for helping out!!

________________________________

**Comment by stevebus** [comment]
No problem --  if you ever need anyone to break things in unexpected and weird ways, I'm your guy!

**Comment by jonbgallant** [comment]
@stevebus - This is now resolved.  You need to enter your username in both server and username like this:

I also updated the readme.

CONTAINER_REGISTRY_SERVER="jongallant" 
CONTAINER_REGISTRY_USERNAME="jongallant"
CONTAINER_REGISTRY_PASSWORD="docker hub password"
