### ISSUE TITLE
Don't file if you try to create a solution that already exists

### ISSUE THREAD

**Issue by jonbgallant** [jonbgallant/azure-iot-edge-dev-tool#50]
```
C:\temp\iotedge>iotedgedev solution debugtest

=============================================================
======== CREATING AZURE IOT EDGE SOLUTION: DEBUGTEST ========
=============================================================

Traceback (most recent call last):
  File "C:\Python27\Scripts\iotedgedev-script.py", line 11, in <module>
    load_entry_point('azure-iot-edge-dev-tool', 'console_scripts', 'iotedgedev')()
  File "c:\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jon\dropbox\code\github\jonbgallant\azure-iot-edge-dev-tool\iotedgedev\cli.py", line 67, in solution
    sol.create(name)
  File "c:\users\jon\dropbox\code\github\jonbgallant\azure-iot-edge-dev-tool\iotedgedev\solution.py", line 25, in create
    os.rename(os.path.join(name, ".env.tmp"), os.path.join(name, ".env"))
WindowsError: [Error 183] Cannot create a file when that file already exists
```

**Comment by shizn** [comment]
Should we just simply skip if the solution folder already exist?
